name: Build and Publish release

on:
  push:
    branches: [ "master", "unstable" ]
  pull_request:
    branches: [ "master", "unstable" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MAX_TOKEN: ${{ secrets.MAX_TOKEN }}
  PKG_NAME: "cosmos-cloud"
  MAINTAINER_NAME: "Yann Stepienik"
  MAINTAINER_EMAIL: "cosmoscloudsup@gmail.com"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set Version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> "$GITHUB_ENV"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: 'amd64,arm64,arm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: install go
        uses: actions/setup-go@v7
        with:
          go-version-file: './go.mod'

      - name: install node
        uses: actions/setup-node@v6
        with:
          node-version: 16
          cache: 'npm'

      - name: install dependencies
        run: |
          npm install
          sudo apt-get update && sudo apt-get install -y musl-tools

      - name: cache GeoLite2-Country database
        id: cache-geolite
        uses: actions/cache@v6
        with:
          path: GeoLite2-Country.mmdb
          key: ${{ runner.os }}-geolite2

      - name: Download GeoLite2-Country database
        if: steps.cache-geolite.outputs.cache-hit != 'true'
        run: |
            curl -s -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=$MAX_TOKEN&suffix=tar.gz" -o GeoLite2-Country.tar.gz
            tar -xzf GeoLite2-Country.tar.gz --strip-components 1 --wildcards "*.mmdb"

      - name: cache Nebula Binary
        id: cache-nebula
        uses: actions/cache@v6
        with:
          path: nebula*
          key: ${{ runner.os }}-nebula

      - name: Download and Extract ARMv7 Nebula Binary
        if: steps.cache-nebula.outputs.cache-hit != 'true'
        run: |
            curl -LO https://github.com/slackhq/nebula/releases/download/v1.8.2/nebula-linux-arm-7.tar.gz
            tar -xzvf nebula-linux-arm-7.tar.gz
            upx -9 nebula

      - name: Rename ARMv7 Nebula Binary
        if: steps.cache-nebula.outputs.cache-hit != 'true'
        run: |
            mv nebula nebula-armv7
            mv nebula-cert nebula-armv7-cert

      - name: Download and Extract ARMv6 Nebula Binary
        if: steps.cache-nebula.outputs.cache-hit != 'true'
        run: |
            curl -LO https://github.com/slackhq/nebula/releases/download/v1.8.2/nebula-linux-arm-6.tar.gz
            tar -xzvf nebula-linux-arm-6.tar.gz
            upx -9 nebula

      - name: Rename ARMv6 Nebula Binary
        if: steps.cache-nebula.outputs.cache-hit != 'true'
        run: |
            mv nebula nebula-armv6
            mv nebula-cert nebula-armv6-cert

      - name: Download and Extract ARM64 Nebula Binary
        if: steps.cache-nebula.outputs.cache-hit != 'true'
        run: |
            curl -LO https://github.com/slackhq/nebula/releases/download/v1.8.2/nebula-linux-arm64.tar.gz
            tar -xzvf nebula-linux-arm64.tar.gz
            upx -9 nebula

      - name: Rename ARM64 Nebula Binary
        if: steps.cache-nebula.outputs.cache-hit != 'true'
        run: |
            mv nebula nebula-arm64
            mv nebula-cert nebula-arm64-cert

      - name: Download and Extract Nebula Binary
        if: steps.cache-nebula.outputs.cache-hit != 'true'
        run: |
            curl -LO https://github.com/slackhq/nebula/releases/download/v1.8.2/nebula-linux-amd64.tar.gz
            tar -xzvf nebula-linux-amd64.tar.gz
            upx -9 nebula

      - name: cache restic Binary
        id: cache-restic
        uses: actions/cache@v6
        with:
          path: restic*
          key: ${{ runner.os }}-restic

      - name: Download and Extract ARM Restic binary
        if: steps.cache-restic.outputs.cache-hit != 'true'
        run: |
            curl -LO https://github.com/restic/restic/releases/download/v0.17.3/restic_0.17.3_linux_arm.bz2
            bunzip2 restic_0.17.3_linux_arm.bz2
            mv restic_0.17.3_linux_arm restic-arm

      - name: Download and Extract ARM64 Restic binary
        if: steps.cache-restic.outputs.cache-hit != 'true'
        run: |
            curl -LO https://github.com/restic/restic/releases/download/v0.17.3/restic_0.17.3_linux_arm64.bz2
            bunzip2 restic_0.17.3_linux_arm64.bz2
            mv restic_0.17.3_linux_arm64 restic-arm64

      - name: Download and Extract Restic binary
        if: steps.cache-restic.outputs.cache-hit != 'true'
        run: |
            curl -LO https://github.com/restic/restic/releases/download/v0.17.3/restic_0.17.3_linux_amd64.bz2
            bunzip2 restic_0.17.3_linux_amd64.bz2
            mv restic_0.17.3_linux_amd64 restic

      - name: Build UI
        run: npm run client-build

      - name: Build
        run: sh build.sh

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=${{ env.VERSION }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=registry,ref=${{ steps.string.outputs.lowercase }}:dockercache
          cache-to: type=registry,ref=${{ steps.string.outputs.lowercase }}:dockercache,mode=max,image-manifest=true
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Prepare package structure       
        run: |
            mkdir -p ${{ env.PKG_NAME }}-${{ env.VERSION }}
            cp -r build/* ${{ env.PKG_NAME }}-${{ env.VERSION }}/
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}/cosmos-launcher-arm*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}/cosmos-arm*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}/nebula-arm*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}/restic-arm*

      - name: Prepare ARMv7 package structure      
        run: |
            mkdir -p ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7
            cp -r build/* ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/cosmos-armv7 ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/cosmos
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/cosmos-launcher-armv7 ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/cosmos-launcher
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/restic-arm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/restic
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/nebula
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/nebula-cert
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/nebula-armv7 ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/nebula
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/nebula-armv7-cert ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/nebula-cert
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/cosmos-launcher-arm64
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/cosmos-arm64
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/nebula-arm64*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7/restic-arm64

      - name: Prepare ARMv6 package structure      
        run: |
            mkdir -p ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6
            cp -r build/* ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/cosmos-armv6 ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/cosmos
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/cosmos-launcher-armv6 ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/cosmos-launcher
            cp ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/restic-arm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/restic
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula-cert
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula-armv6 ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula-armv6-cert ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula-cert
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/cosmos-launcher-arm*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/cosmos-arm*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula-armv7*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/nebula-arm64*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6/restic-arm64

      - name: Prepare ARM64 package structure      
        run: |
            mkdir -p ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64
            cp -r build/* ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/cosmos-arm64 ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/cosmos
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/cosmos-launcher-arm64 ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/cosmos-launcher
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/restic-arm64 ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/restic
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula-cert
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula-arm64 ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula
            mv ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula-arm64-cert ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula-cert
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/cosmos-launcher-arm*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/cosmos-arm*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula-armv6*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/nebula-armv7*
            rm ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64/restic-arm*

      - name: Create .zip packages       
        run: |
            zip -r ${{ env.PKG_NAME }}-${{ env.VERSION }}-amd64.zip ${{ env.PKG_NAME }}-${{ env.VERSION }}
            zip -r ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64.zip ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64
            zip -r ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7.zip ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7
            zip -r ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6.zip ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6

      - name: Generate MD5 hashes    
        run: |
            md5sum ${{ env.PKG_NAME }}-${{ env.VERSION }}-amd64.zip > ${{ env.PKG_NAME }}-${{ env.VERSION }}-amd64.zip.md5
            md5sum ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64.zip > ${{ env.PKG_NAME }}-${{ env.VERSION }}-arm64.zip.md5
            md5sum ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7.zip > ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv7.zip.md5
            md5sum ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6.zip > ${{ env.PKG_NAME }}-${{ env.VERSION }}-armv6.zip.md5

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1      
        with:
          artifacts: "${{ env.PKG_NAME }}-${{ env.VERSION }}-*.zip*"
          tag: v${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          allowUpdates: true
          prerelease: ${{ github.ref != format('refs/heads/{0}', 'master') }}
          makeLatest: ${{ github.ref == format('refs/heads/{0}', 'master') }}
